sudo: false

language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache:
    directories:
        - node_modules
        - $HOME/.composer/cache/files

before_install:
    - rm -rf "$HOME/.nvm"
    - git clone https://github.com/creationix/nvm.git "$HOME/.nvm"
    - source "$HOME/.nvm/nvm.sh"
    - nvm install node
    - npm config set progress false
    - npm install -g npm
    - |
        if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
            phpenv config-rm xdebug.ini
        fi
    - composer self-update

install:
    - npm install
    - composer install --prefer-source

script:
    - npm run-script lint-travis
    - composer test-travis

after_success:
    - |
        if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
            vendor/bin/coveralls --verbose
        fi

notifications:
    email: false

    slack:
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
        rooms:
            - secure: bUvMtbGN/6Lz2S1HMOEempExL6TwSM/Sr8fTn5AnLbVj213nh4z2/9TLPK38Z9pCpgq9gMZuClKJJiA3SRLdJ0V+sEB45H7EYN51wH84Ae7eyDv6325pu9QYR2nbPVabgojDFioG7VIhRSckes+otTUxuE0gge0dfWmG2acMAhpLVJ4uJ+YKJdQEo3Valm/zm5bukP2XPNcvwfsGuPS6S1D0cCHMJNjVfRQxcV5LOZ9piyqw8l9tB48iHKCAYRATrX1ZtoiXSdTKl7NX5I8b1wusdon2HzocZzeU3Wa0Acrf1iByHmYNnAn1W9eeR8noPG3ZyHbAyFhJGr1wlAqp27mUzKC0CIWtp11Gkt4/ReLXee7F0lvqbVsahf5HWnzX3y6/DnvvtrykpnQ2gyIwaWMSgWYZebknSmhXTgYZ16Anjo1fxsLDWoe3GwMN1Nv6hw5LeCulA1GSPCLXvkKfva3mMw7FeJkzvyzIci131/R3d0bUfJ/xNS3RLNZLBZ64APNyP/BxC7LEZBg0w0y6lOlMMOeiTW00YWpMsLQKDflBTWk+4uu7QvOxhUg4x79zzmzroYGSLBaEP3DcfoLebMucWIPhHIk0q+XgmL/rCcoUaEW2cQbBCrNM+cV/tRAEgVCnaSMehpP5avn46fZ9HxF2xNhlvpEUboKLxOGVLLk=
