sudo: false

language: php

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache:
    directories:
        - node_modules
        - $HOME/.composer/cache/files

before_install:
    - rm -rf "$HOME/.nvm"
    - git clone https://github.com/creationix/nvm.git "$HOME/.nvm"
    - source "$HOME/.nvm/nvm.sh"
    - nvm install node
    - npm config set progress false
    - npm install -g npm
    - |
        if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
            phpenv config-rm xdebug.ini
        fi
    - composer self-update

install:
    - npm install
    - composer install --prefer-source

script:
    - npm run-script lint-travis
    - composer test-travis

after_success:
    - |
        if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
            vendor/bin/coveralls --verbose
        fi

notifications:
    email: false

    slack:
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
        rooms:
            - secure: Zy0EpuSgDbq90ObniUPWRY1xesYpDVypxKnI8DFrlf/UB0p2J0s7V8LeM6ddIaKyQSEvsOELYTpReQeCO33QIIQAF6lNFy7o5UQEM9VjHHflTNvIG4ICCQfgp50znXBm8yig9GrH8G/JUjeQAPSowd5xRrX4PD2gODuYuUjIrzflRohzfEFVJieRLkoV8VJRy89uHQ0d7UEvt6q9+2aPYwCtQlMAUTUJFeMNjRV4QeZVhKG8hgoBa0jJcK7k0SfvcinE3SUvnvwxdwvx/m5L+Jgz5xgzXZB02v+flNDhpfr/50ieioFIMtBZ/NhhMh0/3Md6az/xF+QsQ/xA9P4IbISiluqvXtvXIJVWF8Z0ETLRjvLwkIwcexJjlLAnQMtUzvU+Bbmv8DbwBdSMJ6C6OvYwgHIO7g3YWDmlLCSfVPM/K9502d+4wIqdLA5Bx93dvBJSJL0VVQw1yqoJDbxrsMwjbSL2jAUC/ifPk8PHojilUBUqtpdhBPSr5J3Ym+2jscUP8feaw6iG1aiQI9O/YKDeq519dWARyzZ/rVbDMY4S6GJljtsDy8KJofXQDxQvq9Eulkoiwdn9fPrGsdkXSIocPZ4JJHanh3V+xdmIaaTTUdQbzEc9/fLnqAMwdnsa2YDSjPqJRLZngz1Fx22x4UaEVmsJJg2nsXC3A0qH3lY=
